version: '2'

services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - api

volumes:
  pg:

networks:
  api:
    driver: bridge
