import { Toaster } from '@/components/ui/toaster'
import './globals.css'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

const inter = FontSans({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Digital Literacty Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <Toaster />
      </body>
    </html>
  )
}
